version: "3.3"
services:
  mongo:
    container_name: ee-camp-mongo
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ee-camp-mongo:/data/db
    ports:
      - 27017:27017
    restart: on-failure
    command: mongod
volumes:
  ee-camp-mongo:
