name: DockerHub Image PR CI

on:
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set some variables for the image
        run: |
          echo "IMAGE_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cc-server:${steps.branch-name.outputs.current_branch}
            ${{ secrets.DOCKERHUB_USERNAME }}/cc-server:${steps.branch-name.outputs.current_branch}-${{ env.GITHUB_SHA }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: BUILDX_QEMU_ENV=true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
